version: "3"
services:
    wordpress:
        image: wordpress
        depends_on: 
        -   db
        ports:
        -   8080:80

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: wordpress
            MYSQL_USER: "wpuser"
            MYSQL_PASSWORD: 12345678
